PromptConfig:
  base_prompt: 'prompts/base_prompt.txt'

ModelConfig:
  qwen_vl: 'unsloth/Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit'
  # qwen_vl: 'Qwen/Qwen2.5-VL-3B-Instruct'

Dataset:
  max_page: 2

Deploy:
  port: 8077